// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sieve.HR.Services.Db;

#nullable disable

namespace Sieve.HR.Migrations
{
    [DbContext(typeof(HRDbContext))]
    [Migration("20230109053833_department")]
    partial class department
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Sieve.HR.Areas.Admin.Models.HR_COMPANY", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("COMP_ADDR")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("COMP_NAME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MAX_EMP_NO")
                        .HasColumnType("int");

                    b.Property<int>("MAX_SALARY")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("HR_COMPANY");
                });

            modelBuilder.Entity("Sieve.HR.Areas.Admin.Models.HR_DEPARTMENT", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("COMP_ID")
                        .HasColumnType("int");

                    b.Property<string>("DEPT_ADDR")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("DEPT_NAME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("HEAD_EMP_ID")
                        .HasColumnType("int");

                    b.Property<int>("MAX_EMP_NO")
                        .HasColumnType("int");

                    b.Property<int>("MAX_SALARY")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("HR_DEPARTMENT");
                });
#pragma warning restore 612, 618
        }
    }
}
