// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sieve.HR.Services.Db;

#nullable disable

namespace Sieve.HR.Migrations
{
    [DbContext(typeof(HRDbContext))]
    [Migration("20230109083918_foreign key -test")]
    partial class foreignkeytest
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Sieve.HR.Areas.Admin.Models.HR_COMPANY", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("COMP_ADDR")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("COMP_NAME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MAX_EMP_NO")
                        .HasColumnType("int");

                    b.Property<int>("MAX_SALARY")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("HR_COMPANY");
                });

            modelBuilder.Entity("Sieve.HR.Areas.Admin.Models.HR_DEPARTMENT", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("COMP_ID")
                        .HasColumnType("int");

                    b.Property<string>("DEPT_ADDR")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("DEPT_NAME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("HEAD_EMP_ID")
                        .HasColumnType("int");

                    b.Property<int>("MAX_EMP_NO")
                        .HasColumnType("int");

                    b.Property<int>("MAX_SALARY")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("COMP_ID");

                    b.ToTable("HR_DEPARTMENT");
                });

            modelBuilder.Entity("Sieve.HR.Areas.Admin.Models.HR_SECTIONS", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("DEPT_ID")
                        .HasColumnType("int");

                    b.Property<string>("HEAD_EMP_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MAX_EMP_NO")
                        .HasColumnType("int");

                    b.Property<int>("MAX_SALARY")
                        .HasColumnType("int");

                    b.Property<string>("SECT_ADDR")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("SECT_NAME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.HasIndex("DEPT_ID");

                    b.ToTable("HR_SECTIONS");
                });

            modelBuilder.Entity("Sieve.HR.Areas.Admin.Models.HR_DEPARTMENT", b =>
                {
                    b.HasOne("Sieve.HR.Areas.Admin.Models.HR_COMPANY", "HR_COMPANY")
                        .WithMany()
                        .HasForeignKey("COMP_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HR_COMPANY");
                });

            modelBuilder.Entity("Sieve.HR.Areas.Admin.Models.HR_SECTIONS", b =>
                {
                    b.HasOne("Sieve.HR.Areas.Admin.Models.HR_DEPARTMENT", "HR_DEPARTMENT")
                        .WithMany()
                        .HasForeignKey("DEPT_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HR_DEPARTMENT");
                });
#pragma warning restore 612, 618
        }
    }
}
